spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/task_manager_db
    username: iliass
    password: iliass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
app:
  cors:
    allowed-origins: http://localhost:5173
