spring:
  datasource:
    url: jdbc:postgresql://task_manager_postgres:5432/task_manager_db
    username: iliass
    password: iliass
  jpa:
    hibernate:
      ddl-auto: update

app:
    cors:
        allowed-origins: http://localhost
