services:

  frontend:
    container_name: manageProject_frontend
    build: 
      context: ./manageProject-frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:8080/api/v1
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - task_manager_net

  backend:
    container_name: manageProject_backend
    build: ./manageProject-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
       SPRING_PROFILES_ACTIVE: prod 
    networks:
      - task_manager_net

  postgres:
    container_name: task_manager_postgres
    image: postgres
    environment:
      POSTGRES_USER: iliass
      POSTGRES_PASSWORD: iliass
      POSTGRES_DB: task_manager_db
    ports:
      - "5433:5432"
    networks:
      - task_manager_net

networks:
  task_manager_net:
    driver: bridge